### ISSUE TITLE
Exclude Subtitles from loading on the list

### ISSUE THREAD

**Issue by helmyarman** [donmaiq/Mpv-Playlistmanager#10]
I don't know if it's already implemented, But the script loads .SRT files, which is an incorrect behavior.

**Comment by jonniek** [comment]
With no mpv config and using this script I cannot reproduce loading srt files. If it is this script loading them can you give an example how to reproduce this.

Are you sure this is not caused by your mpv conf with a flag such as `sub-auto=all` or are you suggesting this script should override such config?
