### ISSUE TITLE
[Bug] url title reverts to file name

### ISSUE THREAD

**Issue by 2084x** [donmaiq/Mpv-Playlistmanager#108]
To reproduce:

1. open two or more urls with mpv and open the playlist to check titles have resolved

![pic-selected-221213-1224-21](https://user-images.githubusercontent.com/108906685/207203382-7a9a46f6-5cbb-4394-bd4f-28da0f835262.png)

2. wait for first video to end or hit playlist next or hit enter on a playlist entry
3. open playlist again and first entry will just be the file name

![pic-selected-221213-1224-30](https://user-images.githubusercontent.com/108906685/207203951-d33ba99d-de19-4910-94c0-dd5bcbe56598.png)

This is caused by https://github.com/jonniek/mpv-playlistmanager/commit/f00137a91d97cbcbd211b9312a2b4e4b338002fe. Revert to `file-loaded` and the url will resolve. This issue doesn't occur with local files as far as I know.

**Comment by jonniek** [comment]
Seems like the media title is not set yet at this point, since the url is still loading. I feel like there is a lot of issues that have stemmed from that `start-file` change.

I think reverting might cause some other issues since we have adjusted the code a few times already.

I think the correct fix is maybe to have both `start-file` and `file-loaded`.

**Comment by jonniek** [comment]
Made a quick fix. Will take a closer look what belongs in which event later.
