### ISSUE TITLE
playlistmanager "gui" on mpv.net

### ISSUE THREAD

**Issue by candrapersada** [donmaiq/Mpv-Playlistmanager#118]
how to use the above controls from a "gui" on mpv.net?
> If you want to use the above controls from a "gui" rather than keybinds, then you can check out [mpv-menu](https://github.com/jonniek/mpv-menu) and use the menu.json found in this repository

**Comment by jonniek** [comment]
You can do the same thing as `mpv-menu` so sending script messages. I'm not familiar with mpv.net, but it is maybe possible to create UI actions that send script messages.

You can see the supported script messages in the table at the bottom of the readme. For example:
```
script-message playlistmanager show playlist
```

If this doesn't help you figure it out, I would suggest asking for help on mpv.net channels since they will be more familiar with what is possible with their GUI.

If there is some functionality that you need which is not exposed for script-messages such as navigating in the actual opened playlist let me know and I can add them.
