### ISSUE TITLE
How to get duration next to files?

### ISSUE THREAD

**Issue by waxfingers** [donmaiq/Mpv-Playlistmanager#12]
Howdy. Would it be possible to have an option so when I hit *shift + enter* that the names of the loaded files loaded have their duration (hh:mm:ss) appended? It would greatly help sorting /navigating / choosing sequential track names. Thank you 🎳

**Comment by jonniek** [comment]
I don't think this is possible since duration is only known for loaded(currently playing) files. Pretty much the only thing you can get from a playlist is the title/name of the files. Implementing this would require loading the duration data outside of mpv which is prone to errors and os compatibility issues.

**Comment by waxfingers** [comment]
I understand @jonniek Thank you the same for such a useful script and the time to explain to a layman =)
Cheers

PS
I guess this issue can be close {monkey wrench!!!}
