### ISSUE TITLE
Page up / down buttons over scroll and skip files

### ISSUE THREAD

**Issue by Digita1Menace** [donmaiq/Mpv-Playlistmanager#149]
When I use the page up / down buttons, it overscrolls a couple files. I tried to change mpv.conf osd font size, but that doesnt fix the problem. anyone know what I can do to fix this? How is this not an issue already?

**Comment by verygoodlee** [comment]
This is expected behavior, not an issue.
- UP/DOWN moves one row up/down
- PGUP/PGDWN moves one page up/down
https://github.com/jonniek/mpv-playlistmanager/blob/d733d8c00cb543a646f2ce5ab5c12bef2dfd6756/playlistmanager.conf#L16-L19

If you want the PGUP/PGDWN to move one row, change these script options.
```ini
key_moveup=UP PGUP
key_movedown=DOWN PGDWN
key_movepageup=
key_movepagedown=
```

**Comment by Digita1Menace** [comment]
No.. it's an issue. it goes beyond a full page. already switched to a better one.

**Comment by jonniek** [comment]
Yeah it seems to consider the hidden "..." lines as "visible" files, so it skips one file. Also the edge-cases of top and bottom of playlist are not calculated correctly.

One unclear question is if the expected behavior is to skip to the next non visible file, or to skip so much that every visible file is a new file. I feel like the second one is more correct.
