### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by 422658476** [donmaiq/Mpv-Playlistmanager#17]
Hello, author of mpv-playlistmanager:
I am the author of MPV-EASY Player. The extension of the playlist you wrote is very good, so I added this script to MPV-EASY Player long before, as a support for playlists.
However, since MPV-EASY Player supports Simplified Chinese interface and English interface, the playlist also needs to support these two languages. My current practice is to modify your script. I don't know if you can add multi-language support to you. In the original script.
Please refer to my modified script program:

https://github.com/422658476/MPV-EASY-Player/blob/master/portable-data/scripts/playlistmanager.lua

Lines 131 to 134, and lines 181 to 186.

Since I have been updating other code, I have modified the places in playlistmanager.lua that I can't remember. When I update it every time, it may cause new bugs, so I made this request. .

Thank you very much if you can.

**Comment by jonniek** [comment]
Hi, thanks for using playlistmanager in mpv-easy.

In your usecase it might be more convienient to easily toggle between english and mandarin, but I don't think it's a nececcary feature in general. To be able to change the language you need to change a setting, but in the settings  you can already change all the english text to any kind of text(or no text) you want. It would be hard to predict all formats/languages people would like to use so that's why it's user configurable in the first place.

If your users are mainly mandarin speaking then it makes sense for you to change the default playlist setting to mandarin. You could optionally provide 2 separate .config files for english and mandarin settings respectively but that is not as easy for user perhaps.

**Comment by 422658476** [comment]
alright, thank you very much.
Then I will close this issue. Multi-language is really a function that is rarely used for a script. I will still modify it through your original script in the future, which is the least burdensome way for you and me.
Thanks again for the playlist script you provided, it's really easy to use.
