### ISSUE TITLE
Unable to use LEFT key to unselect

### ISSUE THREAD

**Issue by Dupond** [donmaiq/Mpv-Playlistmanager#27]
Hello !

First of all, sorry for my poor english. I'll try to be as accurate as I can.

I find it odd (but it's just my subjective opinion, of course) that when the playlist is visible, the right key is set to both select and unselect the file under the cursor. I think it would make more sense to select with the right key, and unselect with the left one, since each time I don't remember that the left key is not used for this, the default keybind applies (and I rewind my movie 5 seconds).

So I thought I could add the following line in my input.conf file :
`LEFT script-binding tagcurrent`
since the README file says :

> Dynamic keybinds will only work when playlist is visible.

Now I have the behaviour I expected, since I can use both the right and the left keys to select or unselect a file ; except that when the playlist is not displayed, the arrow key doesn't do anything anymore...
I have then tried the following :
`LEFT seek -5 ; script-binding tagcurrent`
but now, when the playlist is displayed, the left keys select or unselect a file AND rewinds my file at the same time...

Any help would be greatly appreciated. Thank you very much !
Best regards,
Dupond

**Comment by jonniek** [comment]
Yeah it seems like you can't really bind dynamic keys in input.conf since it would override any other functionality of that key. The most obvious fix for this is to change it so that dynamic keys are set from settings like so:
```
moveup_key="UP"
movedown_key="DOWN"
...
```
However, this doesn't actually solve your issue since you could still only bind one key per action.

I think I could add untag=LEFT bind together with the above to fix this issue.

**Comment by Dupond** [comment]
That would be awesome !
Obviously, there's no big deal here ; it's not even a bug. It's more like a personal preference, so there's plenty of time to "fix" this ;)
Thank you very much for your great plugin !

**Comment by jonniek** [comment]
Fixed in 284b2ab229655bbb32ad8c1b6f90df5ec8f5c83b

Sorry for taking so long

**Comment by Dupond** [comment]
This is great ! Thank you very much !

So now, from what I've seen, the `RIGHT` key is used to select or unselect, and the `LEFT` key can also be used to unselect.
With your fix, would it be possible to bind the `LEFT` key to unselect OR select too, just like the `RIGHT` key ?
I've tried :
`LEFT script-binding selectfile`
but it doesn't work (it has no effect, nothing happens).
Sorry, I'm not good at that...

**Comment by jonniek** [comment]
It was not possible with that commit. 

I pushed a new update. Now it's possible to bind multiple keys for the same dynamic action by separating them with a space. However, you shouldn't use input conf, since that still has some undesired effects for dynamic binds. You can rebind them at the top of the lua file or by using a `script-opts/playlistmanager.conf` file. I made the default behavior to be what you described, but you can easily change it in the settings if you'd like.

**Comment by Dupond** [comment]
Excellent ! It is super easy to set things directly in the `playlistmanager.conf` file now, even for me ;) Thank you very much for all the time and attention you gave to this. And thank you for your great plugin !
