### ISSUE TITLE
[Feature request] Change playlist file name

### ISSUE THREAD

**Issue by xNissX233** [donmaiq/Mpv-Playlistmanager#50]
It would be great if the script asked you for a name for the playlist when saved, instead of using the default name with the current time (which could be the name if no name is set) so you don´t have to change the file name from the saved folder every time you want to name a playlist.
It would be easily done if you do it like in this script: https://github.com/NurioHin/mpv-bookmarker which has a key bind to rename bookmarks in a list.

**Comment by jonniek** [comment]
I added [playlistmanager-save-interactive.lua](https://github.com/jonniek/mpv-playlistmanager/blob/master/playlistmanager-save-interactive.lua) file as an experiment, using that script will enable you to name your saved playlists.

I'm testing it in a separate file because it's a bit messy with the keybinds, and I would like to make the project more modular.

**Comment by kees-** [comment]
Wow cool! I've wanted exactly this for some time. Pleased to keep an eye out as you develop it
