### ISSUE TITLE
wanna show title with special format

### ISSUE THREAD

**Issue by emacs25** [donmaiq/Mpv-Playlistmanager#58]
the default playlist just shows title name one by one

i just wanna know whether it can be done

the result can show like this below:
```
movie name 1
      episode 01 title one
      episode 02 title two
movie name 2
      episode 01 title one
      episode 02 title two
```
maybe add a shortkey to jump up and down between movie name sections

**Comment by jonniek** [comment]
Can you elaborate what the strucure is made of?

Are movie names directories or files? Are episodes chapters or files?

If you are talking about directories, then it would be outside of the scope of this script, as this is for managing playlists and not files.

If you are talking about chapters, I think it's not easily implemented, since I would imagine chapter data is not available until a file has been loaded. It could perhaps display it for the current file only but I would have to look into that. Back when I developed these scripts I don't think this data was readily available in the lua API.

**Comment by emacs25** [comment]
sorry to ask questions without details

here's my operation

d:/movie. m3u
```
#EXTM3U
#EXTINF:-1
d:/movie/comedy.m3u
#EXTINF:-1
d:/movie/action.m3u
```
action. m3u:
```
#EXTM3U
#EXTINF:-1, title 1
d:/movie/1.mp4
#EXTINF:-1, title 2
http://xxx.m3u8
```
comedy. m3u:
```
#EXTM3U
#EXTINF:-1, title 3
d:/movie/a.mp4
#EXTINF:-1, title 4
http://xxx.m3u8
```
the playlist shows like this:
```
movie
    action
        title 1
        title 2
    comedy
        title 3
        title 4
........ 
```

**Comment by jonniek** [comment]
Since playlists can be recursive this doesn't seem feasible. Also content of the playlist is not available until it loads, so some hack for that would have to be done. This suggestion would also conflict with the editing controls of this script.

I think it's better left for another script to explore such playlist structures.
