### ISSUE TITLE
[Feature Request] Sort playlist by date modified (Directory Opus)

### ISSUE THREAD

**Issue by ghost** [donmaiq/Mpv-Playlistmanager#68]
Hello,

Any chance you can add functionality to create a playlist based upon date modified? I find this very useful for directories that are constantly growing, which I do not want to be played alphabetically. I use directory opus, if that means anything.

Thanks!

**Comment by FichteFoll** [comment]
You can achieve something similar with a simple shell command (on UNIX)
```
ls -1t | mpv --playlist=-
```

**Comment by jonniek** [comment]
I think this usecase is better served by above terminal snippet or a separate script as mpv doesn't natively have access to file information of entire playlist and it would bloat this script even further.

**Comment by hrxn** [comment]
Yeah, this is left best to the shell, I think. Like the example above, this does also work on Windows (with PowerShell):
~`ls -file | sort LastWriteTime -desc | mpv --playlist=-`~
(it is sorted by newest modified first, like `ls -t`)

*Edit:*

~I just realized, while the above works on my machine™, this depends on your PS version and also some PS settings...~

Long story short, if the above *does* not work, we simply have to do this one extra step:
`ls -file | sort LastWriteTime -desc | select -expand FullName | mpv --playlist=-`

*Edit 2:*

Fixed incorrect information from earlier, it was "working" for me because I had 'mpv' as an alias and was actually running a custom wrapper script...
It does not and cannot work with PS as initially stated, because `--playlist=-` reads a "playlist" from stdin, and with PS you have to use the extra step to "unpack" the objects to get at the plain string, then it is working with `--playlist=-`

Sorry for any potential confusion...

**Comment by ghost** [comment]
Thanks Hrxn, I'll give this a try!

**Comment by ghost** [comment]
Tried adding mpv's exe folder path as an environmental variable, as mpv was not recognized. It still couldn't find it, so after this I tried both above commands on Windows, but instead of mpv I input "PATHTOMPV.EXE", and I got errors "expressions are only allowed as the first element of the pipeline."

Am I doing something wrong?

**Comment by hrxn** [comment]
You mean, for example, ` ...  | 'D:\Programs\mpv\mpv.exe' --playlist=-` instead of ` ... | mpv --playlist=-`?

Yeah, it does not work in this instance, because PS sees `"string"` (or `'string'`) as an as-is-value in an expression, this is simply how the parser works.

In such a case you have to be explicit that you are trying to run a command.
You can do this, for example, by using the call-operator (`&`)
I.e. like this:
`ls -file | sort LastWriteTime -desc | select -expand FullName | & "C:\mydir\myfiles\mpv.exe" --playlist=-`

One more thing to add, because of how mpv works on Windows:
While running `mpv.exe` is perfectly fine, if you want to actually see it attached to the console you might want to use `mpv.com` instead.

(By default on Windows, if you have your `%PATH%` set up correctly, typing `mpv` on the command line actually uses `mpv.com` (because it comes earlier in `%PATHEXT%`))

**Comment by ghost** [comment]
The following command did work:
`ls -file | sort LastWriteTime -desc | select -expand FullName | & 'C:\Program Files\mpv\mpv-x86_64-20210404-git-dd86f19\mpv.exe" --playlist=-`

Though it was slightly different from your example command that used " and ' instead of a pair of 's

Few oddities, though. MPV doesn't actually run until I close the console window. Perhaps there's a way to make this happen automatically?

Also, for some reason if I progress the playlist, close the video, running the command will resume the playlist from where I left off, instead of back at the beginning.

**Comment by hrxn** [comment]
Yeah, sorry, guess the example was fat-fingered somehow..
You can use either ` " ... " ` *or* ` ' ... ' ` - both are string literals in PowerShell.

The former (double-quoted string) is called expandable string, the latter (single-quoted string) is called verbatim string.

Expandable strings can do variable substitution and subexpressions, but we don't have any variable inside our string here, so there is basically no difference in our case here.

> Few oddities, though. MPV doesn't actually run until I close the console window. Perhaps there's a way to make this happen automatically?

That sounds strange. Do you use any third-party console or something? If you run `mpv.com` instead of `mpv.exe` you should definitely see the status messages printed by mpv...

> Also, for some reason if I progress the playlist, close the video, running the command will resume the playlist from where I left off, instead of back at the beginning.

As if `save-position-on-quit` is somewhere used in your configuration?
You could make sure by using the `--no-resume-playback` mpv option on the command line, if this changes the behaviour it's definitely some Watch Later option..

**Comment by ghost** [comment]
Got it, thanks so much.
