### ISSUE TITLE
bug: this script will add extra files incorrectly when dropping folders into mpv

### ISSUE THREAD

**Issue by dyphire** [donmaiq/Mpv-Playlistmanager#89]
Prerequisite: enable the option of `loadfiles_on_start=yes`.

 Directory example: 
```
│   video-1.mp4
│   video-2.mp4
│
└───test
    ├───test-1.mp4
    ├───test-2.mp4
    ├───test-3.mp4
```
1. dropping the `test` folder into mpv.
2. expected behavior: added test-1.mp4, test-2.mp4, test-3.mp4
3. actual behavior: also added video-1.mp4, video-2.mp4

It seems that this script has done some strange things.

example video:

https://user-images.githubusercontent.com/61936050/197541475-812de4b1-0a9e-43a0-8936-00d32a70e7ec.mp4

**Comment by dyphire** [comment]
It can be confirmed that the error introduced by this commit https://github.com/jonniek/mpv-playlistmanager/commit/f00137a91d97cbcbd211b9312a2b4e4b338002fe.
still don't know why.

**Comment by jonniek** [comment]
Seems like the start-file is running twice. Once for the directory, and then again for the file. 

My testing doesn't reproduce your result, it just loads the test directory twice, leading to test 2 and test 3 files being duplicated in the playlist.

I think in your case it is perhaps loading from the working directory instead of the test directory. You can maybe double check by using the keybind to load playlist before dropping the test directory.
```lua
if plen == 0 then
    hasfile = false
    dir = mp.get_property('working-directory')
else
```
For me the playlist length is 1, so it doesn't use the working-directory but rather `directory` which is the path of the test directory.

Anyway I don't think we should execute the on_loaded if we are opening a directory. That seems to fix at least this case, and I can't think of any issues it should cause.

**Comment by dyphire** [comment]
The commit https://github.com/jonniek/mpv-playlistmanager/commit/655303855811104aa363aa502b89ab0536e63167 does not fixes this issue, It need be reopened.

https://user-images.githubusercontent.com/61936050/199222767-a0aa7e85-0418-4054-be38-30142e959fed.mp4

This is test log, hope it can help: [test.log.txt](https://github.com/jonniek/mpv-playlistmanager/files/9909359/test.log.txt)

**Comment by dyphire** [comment]
I opened a pr to implement correctly avoid loading a directory.
